Add groupBy to FindAll
AndcultureCode/AndcultureCode.CSharp.Core pull request #60
Opened 2020-10-18 14:47 UTC by dzoccarato

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [ ] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Issue: #48 

**Note:**
1. `FindAll` has an overload to accept group by clause.
Made this choice because GroupBy returns `IQueryable<IGrouping<TKey, TSource>>` instead of `IQueryable<TSource>` (https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq.Queryable/src/System/Linq/Queryable.cs)
2. changes on `IRepository.cs` needed to be able to use `FindAll` it on `RepositoryReadConductor` of `AndcultureCode.CSharp.Conductors` project

Is this acceptable for you?

2020-10-20 00:18 UTC, brandongregoryscott requested changes
Thanks for the PR @dzoccarato! Just some minor cleanup/formatting I am requesting. Once this is merged and published, I'll take a look at the PR for Conductors.

2020-10-20 00:18 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Core/Interfaces/Data/IRepository.cs
> +        /// Find all filtered, sorted and paged
Minor: Can you update this to include something describing the grouping by property?

Also, if you don't mind breaking out the parameters in the signature by new line, that would help with readability 👍 I realize you were going off of how the rest of the file is structured, but it'd probably go a long way if readers didn't have to horizontally scroll for the whole signature.

2020-10-20 00:18 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +        /// <param name="groupBy"></param>
I realize the rest of this xml doc is missing comments, but would you mind filling in what `groupBy` is used for? Something along the lines of "Property or properties of the entity to group results by"

2020-10-20 00:18 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +
Super minor - but since you're in here, can you remove this unnecessary new line?

2020-10-20 04:48 UTC, dzoccarato commented
@brandongregoryscott thanks for your review!
I'll update this PR with reviews you requested!

2020-10-20 06:28 UTC, dzoccarato commented on src/AndcultureCode.CSharp.Core/Interfaces/Data/IRepository.cs
> +        /// Find all filtered, sorted and paged
should resolved by https://github.com/dzoccarato/AndcultureCode.CSharp.Core/commit/44ba9895d0c3f26d09565a9c2d68ca4e4b4f053a

2020-10-20 06:29 UTC, dzoccarato commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +        /// <param name="groupBy"></param>
should resolved by https://github.com/dzoccarato/AndcultureCode.CSharp.Core/commit/e4af04d7327d15d1e143686b5443302dd0cf82c7

2020-10-20 06:29 UTC, dzoccarato commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +
should resolved by https://github.com/dzoccarato/AndcultureCode.CSharp.Core/commit/e4af04d7327d15d1e143686b5443302dd0cf82c7

2020-10-20 06:30 UTC, dzoccarato commented
Hi @brandongregoryscott , I've pushed the changes you request, can you take a look at the latest commits? thanks!

2020-10-20 20:01 UTC, mrjones2014 requested changes
@dzoccarato what you have here is great. However, `GroupBy` has [another overload](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.groupby?view=netcore-3.1#System_Linq_Queryable_GroupBy__3_System_Linq_IQueryable___0__System_Linq_Expressions_Expression_System_Func___0___1___System_Linq_Expressions_Expression_System_Func___1_System_Collections_Generic_IEnumerable___0____2___) which returns a `IQueryable<TResult>`.

Can you add another set of overloads that would use this overload of `GroupBy`, which would allow us to return `IQueryable<TResult>` instead of an `IQueryable<IGrouping<T, TKey>>`?

2020-10-20 20:03 UTC, brandongregoryscott requested changes

2020-10-20 20:03 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +            Func<IQueryable<T>, IOrderedQueryable<T>> orderBy   = null,
Sorry for the back & forth here @dzoccarato - we don't align anymore (anything else in this file that is aligned is an old artifact), saving this in an editor like VS Code with the C# extension _should_ revert the alignment to the MS formatting standard.

2020-10-20 20:34 UTC, dzoccarato commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +            Func<IQueryable<T>, IOrderedQueryable<T>> orderBy   = null,
@brandongregoryscott , this is not a problem: I've removed alignment in this commit : https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/pull/60/commits/399ba34eee8f31c3a08d30a55b92080d4296e6ef

2020-10-20 20:41 UTC, dzoccarato commented
> @dzoccarato what you have here is great. However, `GroupBy` has [another overload](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.groupby?view=netcore-3.1#System_Linq_Queryable_GroupBy__3_System_Linq_IQueryable___0__System_Linq_Expressions_Expression_System_Func___0___1___System_Linq_Expressions_Expression_System_Func___1_System_Collections_Generic_IEnumerable___0____2___) which returns a `IQueryable<TResult>`.
> 
> Can you add another set of overloads that would use this overload of `GroupBy`, which would allow us to return `IQueryable<TResult>` instead of an `IQueryable<IGrouping<T, TKey>>`?

@mrjones2014 , thanks for your feedback!
Just to make me an idea, looking at the documentation you shared me, this `groupby` overload transform the `IQueryable<TSource>` into `IQueryable<TResult>`, is ok for you a signature like this one?

```cs
public interface IRepositoryReadConductor<T>
{
   // other stuff

   IResult<IQueryable<TResult>> FindAll<TKey, TResult>(..)

   // other stuff
}
```
where the purpose is transform the grouped of type "`<T>`" into a (potentially) different `TResult` ?

2020-10-21 11:26 UTC, mrjones2014 requested changes

2020-10-21 11:26 UTC, mrjones2014 commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +        /// ref to: https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.groupby?view=netcore-3.1#System_Linq_Queryable_GroupBy__3_System_Linq_IQueryable___0__System_Linq_Expressions_Exp
consider running this through a URL shortener

2020-10-21 11:26 UTC, mrjones2014 commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +            Expression<Func<TKey, IEnumerable<T>, T>> groupBySelector = null,
I think you need to introduce another type generic, `TResult`.  `groupBySelector` should return `TResult`, which doesn't have to be the same as `T` (it can be anything).

For example, if `groupBySelector` is defined as `(key, group) => group.Select(e => e.Id)`, then `TResult` would be of type `long` (if you're using `Auditable`s), and the `FindAll` method would return `IResult<IQueryable<long>>`.

@brandongregoryscott correct me if I'm wrong but I think the type for `groupBySelector` should be `Expression<Func<TKey, IEnumerable<T>, TResult>>`?

2020-10-21 11:26 UTC, mrjones2014 commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +            Expression<Func<T, bool>> filter = null,
thanks for taking the time to fix the other formatting issues in this file!

2020-10-21 16:47 UTC, dzoccarato commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +        /// ref to: https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.groupby?view=netcore-3.1#System_Linq_Queryable_GroupBy__3_System_Linq_IQueryable___0__System_Linq_Expressions_Exp
done in: https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/pull/60/commits/dad1bdf36b712135174b75feb64ee006af933094

2020-10-21 16:53 UTC, dzoccarato commented on src/AndcultureCode.CSharp.Core/Interfaces/Conductors/IRepositoryReadConductor.cs
> +            Expression<Func<TKey, IEnumerable<T>, T>> groupBySelector = null,
@mrjones2014 honestly, I've committed those venison `Expression<Func<TKey, IEnumerable<T>, T>> groupBySelector = null` by mistake: was just a try to clarify to me what was the best approach.
If you look to commit: https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/pull/60/commits/28e31e52979b02576ba1fbd57ff55c26bd4c7479 I've rolled back my changes because the purpose of those commit was fix the alignment. Changes that I've committed again in next one (https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/pull/60/commits/f2995968a17d6047093fb45c4100d4294576b225).

I suppose what you are looking for, is the commit I've just made: https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/pull/60/commits/dad1bdf36b712135174b75feb64ee006af933094, where the groupBySelector indeed is `Expression<Func<TKey, IEnumerable<T>, TResult>> groupBySelector = null`

2020-10-21 16:54 UTC, dzoccarato commented
@brandongregoryscott, @mrjones2014  If you want to take a look at last commit I've added the interfaces for the group by and selector `IResult<IQueryable<TResult>> FindAll<TKey, TResult>`

2020-10-21 17:01 UTC, mrjones2014 requested changes
@dzoccarato looks great. Can you just revert the markdown files? these will get auto-generated when we build and release a new version of the package. The way they are right now, the repo links would point to your fork.

2020-10-21 18:34 UTC, dzoccarato commented
> @dzoccarato looks great. Can you just revert the markdown files? these will get auto-generated when we build and release a new version of the package. The way they are right now, the repo links would point to your fork.

@mrjones2014 , should done on latest commit, please can you check if looks as expected?

2020-10-22 11:22 UTC, brandongregoryscott approved these changes

2020-10-22 11:24 UTC, merged

2020-10-22 11:35 UTC, brandongregoryscott commented
Thanks for the contribution @dzoccarato - I'll publish this when I'm on my main workstation here in a few minutes and update this with the version number.

2020-10-22 12:33 UTC, brandongregoryscott commented
Published with [v0.7.0](https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/releases/tag/v0.7.0)

2020-10-22 16:14 UTC, dzoccarato commented
@brandongregoryscott  thanks!
I've just update the package version on branch of PR on AndcultureCode.CSharp.Conductors: https://github.com/AndcultureCode/AndcultureCode.CSharp.Conductors/pull/24#.