Add find by id method overload
AndcultureCode/AndcultureCode.CSharp.Core pull request #66
Opened 2020-11-06 19:29 UTC by SaidShah

…the XML docs

- [ x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Closes #61

2020-11-06 20:20 UTC, brandongregoryscott approved these changes

2020-11-06 20:20 UTC, brandongregoryscott commented
Thanks for taking the extra time to fill in the XML comments, too!

2020-11-06 20:22 UTC, merged

2020-11-06 20:22 UTC, jstevenson requested changes

2020-11-06 20:22 UTC, jstevenson commented on src/AndcultureCode.CSharp.Core/AndcultureCode.CSharp.Core.md
> +  - [FindById(id,includeProperties)](#M-AndcultureCode-CSharp-Core-Interfaces-Conductors-IRepositoryReadConductor`1-FindById-System-Int64,System-String[]- 'AndcultureCode.CSharp.Core.Interfaces.Condu
I am not sure if this should be sorted by input names, but you at least group the two `FindById(id,includeProperties)` methods.

2020-11-06 20:22 UTC, jstevenson commented on src/AndcultureCode.CSharp.Core/AndcultureCode.CSharp.Core.md
> +  - [FindById(id,includeProperties)](#M-AndcultureCode-CSharp-Core-Interfaces-Data-IRepository`1-FindById-System-Int64,System-String[]- 'AndcultureCode.CSharp.Core.Interfaces.Data.IRepository`1.FindB
Same here

2020-11-06 20:22 UTC, jstevenson commented on src/AndcultureCode.CSharp.Core/AndcultureCode.CSharp.Core.md
> +### FindById(id,includeProperties) `method`
And here

2020-11-06 20:22 UTC, jstevenson commented on src/AndcultureCode.CSharp.Core/AndcultureCode.CSharp.Core.md
> +### FindById(id,includeProperties) `method`
And here

2020-11-06 20:28 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Core/AndcultureCode.CSharp.Core.md
> +  - [FindById(id,includeProperties)](#M-AndcultureCode-CSharp-Core-Interfaces-Conductors-IRepositoryReadConductor`1-FindById-System-Int64,System-String[]- 'AndcultureCode.CSharp.Core.Interfaces.Condu
This file is autogenerated 👍

2020-11-06 20:31 UTC, jstevenson commented on src/AndcultureCode.CSharp.Core/AndcultureCode.CSharp.Core.md
> +  - [FindById(id,includeProperties)](#M-AndcultureCode-CSharp-Core-Interfaces-Conductors-IRepositoryReadConductor`1-FindById-System-Int64,System-String[]- 'AndcultureCode.CSharp.Core.Interfaces.Condu
> This file is autogenerated 👍

Said just mentioned that to me also. I guess the source was out of order.  🤦

2021-04-08 13:56 UTC, wintondeshong commented
@all-contributors please add @SaidShah for documentation